#!/usr/bin/env bash

# deletes every file in given directory created older than today

path="/absolute/path/"

if [ $# -eq 1 ]; then
	path=$1
fi

echo $path

for dire in $(ls -F $path | grep \/); do
	if [ `ls -ld $path$dire | cut -d' ' -f11` != `date | cut -d' ' -f4` ]; then
	echo $path$dire
	rm -rf $path$dire
	fi
done

exit 0

